document.title = "艦これ　装備開発ツール"
document.body.lang = "ja"
var dict = { "KanColle Development Tools": "艦これ　装備開発ツール",
"Development Simulator & Recipe Generator": "開発シミュレータ&複合レシピジェネレータ",
"Development Simulator": "開発シミュレータ",
"Recipe Generator": "複合レシピジェネレータ",
"Probability Table": "確率一覧表",
"Fuel": "燃料",
"Ammunition": "弾薬",
"Ammu": "弾薬",
"Steel": "鋼材",
"Bauxite": "ボーキ",
"Dev. Mat.": "開発資材",
"Secretary": "秘書艦",
"HQ Level": "司令部LV",
"Torpedo Family": "水雷系",
"Gunboat Family": "砲戦系",
"Carrier Family": "空母系",
"Min ": "最低",
"No Result": "結果がない",
"Details": "詳細",
"Expected Resource Consumption": "予想した資源の使用量",
"Get Target": "目安を入手",
"Develop": "開発",
"Success Rate": "成功率",
"Failure Rate": "失敗率",
"Name": "名称",
"Percentage": "確率",
"Failed": "失敗",
"Internal": "内部の",
"Rarity": "レア度",
"(\\d{1,2}%) when (.*?) is available": "$2 が出る時の確率は $1",
"Only available when\r?\nmaterial is greater than\r?\n([0-9\\/]*)": "材料使用量が\n$1\n以上の場合のみ",
"Require Italian Flagship": "イタリア艦を秘書艦に\n任命する必要があります",
"Require(\\r?\\n| )([\\w\\W]*)": "$2$1を必要とする",
"Italian Flagship": "イタリア艦を秘書艦に任命する",
"No records for Luigi Torelli and Aquila": "Luigi Torelli と Aquila に関する記録はありません",
"Project Homepage": "ホームページへ",
"Feedback": "フィードバック",
"Data Source\\(Chinese\\)": "データのソース（中国語）" }

var itemtypenames = [ "小口径主砲",
"中口径主砲",
"大口径主砲",
"副砲",
"対空機銃",
"対空強化弾",
"対艦強化弾",
"魚雷 & 特殊潜航艇",
"艦上戦闘機",
"艦上攻撃機",
"艦上爆撃機",
"艦上偵察機",
"水上機",
"レーダー",
"ソナー & 爆雷",
"機関部強化",
"増設バルジ",
"陸上攻撃機",
"簡易輸送部材" ]