document.title = "舰队Collection 开发工具"
var dict = { "KanColle Development Tools": "舰队Collection 开发工具",
"Development Simulator & Recipe Generator": "开发模拟器 & 复合公式生成器",
"Development Simulator": "开发模拟器",
"Recipe Generator": "复合公式生成器",
"Probability Table": "概率一览表",
"Fuel": "油",
"Ammunition": "弹",
"Ammu": "弹",
"Steel": "钢",
"Bauxite": "铝",
"Dev. Mat.": "开发资材",
"Secretary": "秘书舰",
"HQ Level": "提督等级",
"Torpedo Family": "水雷系",
"Gunboat Family": "炮舰系",
"Carrier Family": "航母系",
"Require": "需要",
"Min ": "最低",
"No Result": "无结果",
"Details": "详细",
"Expected Resource Consumption": "期望出货消耗",
"Get Target": "出货",
"Develop": "开发",
"Success Rate": "成功率",
"Failure Rate": "失败率",
"Name": "名称",
"Percentage": "概率",
"Failed": "失败",
"Internal": "内部",
"Rarity": "稀有度",
"(\\d{1,2}%) when (.*?) is available": "$2 加入列表时为 $1",
"Only available when\r?\nmaterial is greater than\r?\n([0-9\\/]*)": "仅资源投入达到\n$1\n时加入列表",
" ?Italian Flagship": "意舰旗舰",
"No records for Luigi Torelli and Aquila": "Luigi Torelli、Aquila 无出货记录",
"Project Homepage": "项目页面",
"Feedback": "反馈",
"Data Source\\(Chinese\\)": "数据来源" }

var itemtypenames = [ "小口径主炮",
"中口径主炮",
"大口径主炮",
"副炮",
"机枪",
"对空强化弹",
"穿甲弹",
"鱼雷 & 微型潜艇",
"舰载战斗机",
"舰载鱼雷机",
"舰载轰炸机",
"舰载侦查机",
"水上机",
"电探",
"对潜装备",
"引擎",
"增设装甲板",
"路基攻击机",
"简易运输桶" ]